env:
  browser: true
  es6: true
  jest: true
extends: airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  global-require: 0
  import/no-extraneous-dependencies: 0
  react/jsx-filename-extension: 0
  prefer-destructuring: 0
  react/destructuring-assignment: 0
  react/no-access-state-in-setstate: 0
  react/forbid-prop-types: 0
